// @ts-check

/**
 * The sidebar is autogenerated from the folder structure. Ordering and labels
 * come from each folder's _category_.json, so adding a page never means
 * editing this file.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
